version: "2"
services:
  dm-migration:
    depends_on:
      - db
    build: .
    volumes:
      - .:/app
#    ports:
#      - "4000:4000"
#      - "9229:9229"
    command: "npm run migrate"
    restart: on-failure
    environment:
      DB_HOST: db
      DB_USER: push_notifs
      DB_PASSWORD: push_notifs
      DB_DATABASE: push_notifs
      DB_PORT: 5432

  app:
    depends_on:
      - db
    build: .
    volumes:
      - .:/app
    ports:
      - "4000:4000"
      - "9229:9229"
    command: "npm run start:debug"
    restart: always
    environment:
      DB_HOST: db
      DB_USER: push_notifs
      DB_PASSWORD: push_notifs
      DB_DATABASE: push_notifs
      DB_PORT: 5432

  db:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: push_notifs
      POSTGRES_PASSWORD: push_notifs
      POSTGRES_DB: push_notifs